version: '3.4'

services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    expose:
    - 27017
    ports:
    - 27017:27017
    volumes:
    - mongodatavolume:/data/db
    # environment:
    # - MONGO_INITDB_ROOT_USERNAME=usermradminpants
    # - MONGO_INITDB_ROOT_PASSWORD=y5Trogldytes123!

volumes:
  mongodatavolume:
