version: "3.7"
services:
  postgisdb:
    image: postgis/postgis:latest
    #restart: always
    environment:
      #POSTGRES_DB: postgres
      name: blerf-postgis
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./pgisdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    
  pgadmin:
    image: dpage/pgadmin4:latest
    #restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@blerftron.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - ./pgadmindata:/var/lib/pgadmin
    links:
      - "postgisdb:postgis-server"
# volumes:
#   db-data:
#   pgadmin-data: